import React, { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import DefaultHeader from '@/components/header/default-header';
import Footer4 from '@/components/footer/footer-4';
import { api } from '@/utils/apiProvider';

/* ============================================================================
   📊 READINESS REPORT PAGE - STEP 4-6 IMPLEMENTATION
   ============================================================================
   
   STEP 4: Report Layout (Logical Sections)
   1. Header (Logo, User name, Target role, Generated date)
   2. Readiness Summary (Score %, Status, Last calculated)
   3. Skill Breakdown (Table: Skill | Status | Source | Importance)
   4. Roadmap Priorities (High/Medium/Low + Why this matters)
   5. Progress Snapshot (Last 3 scores, Trend direction)
   6. Footer (Generated by RoleReady, Explainability note)
   
   STEP 5: Frontend Trigger - Export button on readiness/roadmap pages
   
   STEP 6: Guardrails
   - No readiness → disable export
   - No roadmap → still export summary
   - Validation pending → show disclaimer
   
   ============================================================================ */

const ReadinessReportPage = () => {
  const navigate = useNavigate();
  const reportRef = useRef(null);
  
  // State
  const [report, setReport] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const [isExporting, setIsExporting] = useState(false);
  
  // Get user from localStorage
  const user = JSON.parse(localStorage.getItem('user'));
  const user_id = user?.user_id;
  
  useEffect(() => {
    if (!user_id) {
      toast.warning('Please login to view your report');
      navigate('/login');
      return;
    }
    
    fetchReport();
  }, [user_id]);
  
  const fetchReport = async () => {
    setIsLoading(true);
    setError(null);
    
    try {
      const response = await fetch(`${api}/api/report/${user_id}`);
      const data = await response.json();
      
      if (data.success) {
        console.log('[Report] API Response:', data);
        console.log('[Report] Roadmap data:', data.report?.roadmap);
        
        // Deduplicate skills by skill_id to prevent duplicates
        if (data.report?.skill_breakdown) {
          const deduplicateSkills = (skills) => {
            const seen = new Set();
            return skills.filter(skill => {
              if (seen.has(skill.skill_id)) {
                return false;
              }
              seen.add(skill.skill_id);
              return true;
            });
          };
          
          data.report.skill_breakdown.met_skills = deduplicateSkills(
            data.report.skill_breakdown.met_skills || []
          );
          data.report.skill_breakdown.missing_skills = deduplicateSkills(
            data.report.skill_breakdown.missing_skills || []
          );
          
          // Recalculate counts after deduplication
          data.report.skill_breakdown.met_count = data.report.skill_breakdown.met_skills.length;
          data.report.skill_breakdown.missing_count = data.report.skill_breakdown.missing_skills.length;
          data.report.skill_breakdown.total_skills = 
            data.report.skill_breakdown.met_count + data.report.skill_breakdown.missing_count;
        }
        
        setReport(data);
      } else {
        setError({
          type: data.error === 'NO_READINESS' ? 'no_readiness' : 'error',
          message: data.message
        });
      }
    } catch (err) {
      setError({
        type: 'error',
        message: 'Failed to load report. Please try again later.'
      });
    } finally {
      setIsLoading(false);
    }
  };
  
  // Handle print
  const handlePrint = () => {
    window.print();
  };
  
  // Handle PDF export using html2pdf.js (loaded dynamically)
  const handleExportPDF = async () => {
    setIsExporting(true);
    
    try {
      const html2pdf = (await import('html2pdf.js')).default;
      
      const element = reportRef.current;
      const userName = report?.report?.user?.name || 'User';
      const date = new Date().toISOString().split('T')[0];
      
      const opt = {
        margin: [10, 10, 10, 10],
        filename: `readiness-report-${userName.replace(/\s+/g, '-')}-${date}.pdf`,
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: { scale: 2, useCORS: true },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
      };
      
      await html2pdf().set(opt).from(element).save();
      toast.success('Report exported successfully!');
      
    } catch (err) {
      console.error('PDF export error:', err);
      toast.error('Failed to export PDF. Try using the Print option instead.');
    } finally {
      setIsExporting(false);
    }
  };
  
  // Calculate trend from history (last 3 entries)
  const calculateTrend = (history) => {
    if (!history || history.length < 2) return { direction: 'stable', icon: '➡️', color: '#6b7280' };
    
    const recent = history.slice(0, 3);
    const newest = recent[0]?.percentage || 0;
    const oldest = recent[recent.length - 1]?.percentage || 0;
    const diff = newest - oldest;
    
    if (diff > 5) return { direction: 'up', icon: '📈', color: '#16a34a', text: `+${diff}% improvement` };
    if (diff < -5) return { direction: 'down', icon: '📉', color: '#dc2626', text: `${diff}% decline` };
    return { direction: 'stable', icon: '➡️', color: '#6b7280', text: 'Stable' };
  };
  
  // Get source label
  const getSourceLabel = (source) => {
    switch (source) {
      case 'self': return 'Self-claimed';
      case 'resume': return 'Resume';
      case 'validated': return 'Mentor ✓';
      default: return source || 'Unknown';
    }
  };
  
  // Status badge component
  const StatusBadge = ({ label, color, size = 'normal' }) => {
    const colorMap = {
      danger: { bg: '#fee2e2', text: '#dc2626', border: '#fca5a5' },
      warning: { bg: '#fef3c7', text: '#d97706', border: '#fcd34d' },
      success: { bg: '#dcfce7', text: '#16a34a', border: '#86efac' },
      primary: { bg: '#dbeafe', text: '#2563eb', border: '#93c5fd' }
    };
    
    const colors = colorMap[color] || colorMap.primary;
    const padding = size === 'small' ? '2px 8px' : '4px 12px';
    const fontSize = size === 'small' ? '12px' : '14px';
    
    return (
      <span style={{
        display: 'inline-block',
        padding,
        borderRadius: '9999px',
        fontSize,
        fontWeight: '600',
        backgroundColor: colors.bg,
        color: colors.text,
        border: `1px solid ${colors.border}`
      }}>
        {label}
      </span>
    );
  };
  
  // Progress bar component
  const ProgressBar = ({ percentage, color = 'primary', height = 12 }) => {
    const colorMap = {
      danger: '#dc2626',
      warning: '#d97706',
      success: '#16a34a',
      primary: '#2563eb'
    };
    
    return (
      <div style={{
        width: '100%',
        height: `${height}px`,
        backgroundColor: '#e5e7eb',
        borderRadius: '6px',
        overflow: 'hidden'
      }}>
        <div style={{
          width: `${Math.min(percentage, 100)}%`,
          height: '100%',
          backgroundColor: colorMap[color] || colorMap.primary,
          borderRadius: '6px',
          transition: 'width 0.5s ease'
        }} />
      </div>
    );
  };
  
  // Loading state
  if (isLoading) {
    return (
      <>
        <DefaultHeader />
        <section className="pt-40 pb-40" style={{ backgroundColor: '#f9fafb', minHeight: '100vh' }}>
          <div className="container">
            <div style={{ textAlign: 'center', padding: '60px 20px' }}>
              <div className="spinner-border text-primary" role="status" style={{ width: '48px', height: '48px' }}>
                <span className="visually-hidden">Loading...</span>
              </div>
              <p style={{ marginTop: '16px', color: '#6b7280' }}>Generating your readiness report...</p>
            </div>
          </div>
        </section>
        <Footer4 />
      </>
    );
  }
  
  // Error state - STEP 6: Guardrail for no readiness
  if (error) {
    return (
      <>
        <DefaultHeader />
        <section className="pt-40 pb-40" style={{ backgroundColor: '#f9fafb', minHeight: '100vh' }}>
          <div className="container">
            <div style={{ 
              maxWidth: '600px', 
              margin: '60px auto', 
              textAlign: 'center',
              padding: '40px',
              backgroundColor: '#fff',
              borderRadius: '12px',
              boxShadow: '0 1px 3px rgba(0,0,0,0.1)'
            }}>
              {error.type === 'no_readiness' ? (
                <>
                  <div style={{ fontSize: '48px', marginBottom: '16px' }}>📊</div>
                  <h2 style={{ fontSize: '24px', fontWeight: '600', marginBottom: '12px' }}>
                    No Readiness Data Found
                  </h2>
                  <p style={{ color: '#6b7280', marginBottom: '24px' }}>
                    You need to calculate your readiness score before generating a report.
                  </p>
                  <button
                    onClick={() => navigate('/readiness')}
                    className="btn btn-primary"
                    style={{ padding: '12px 24px' }}
                  >
                    Calculate Readiness First
                  </button>
                </>
              ) : (
                <>
                  <div style={{ fontSize: '48px', marginBottom: '16px' }}>⚠️</div>
                  <h2 style={{ fontSize: '24px', fontWeight: '600', marginBottom: '12px' }}>
                    Error Loading Report
                  </h2>
                  <p style={{ color: '#6b7280', marginBottom: '24px' }}>
                    {error.message}
                  </p>
                  <button
                    onClick={fetchReport}
                    className="btn btn-primary"
                    style={{ padding: '12px 24px' }}
                  >
                    Try Again
                  </button>
                </>
              )}
            </div>
          </div>
        </section>
        <Footer4 />
      </>
    );
  }
  
  const { user: reportUser, readiness, skill_breakdown, validation, roadmap, history } = report?.report || {};
  const trend = calculateTrend(history);
  const hasPendingValidation = validation?.pending_validation > 0;
  
  // Combine all skills for table view
  const allSkills = [
    ...(skill_breakdown?.met_skills || []).map(s => ({ ...s, status: 'met' })),
    ...(skill_breakdown?.missing_skills || []).map(s => ({ ...s, status: 'missing' }))
  ];
  
  return (
    <>
      <DefaultHeader />
      
      {/* Action Bar - Hidden during print */}
      <div className="no-print" style={{
        position: 'sticky',
        top: '80px',
        zIndex: 100,
        backgroundColor: '#fff',
        borderBottom: '1px solid #e5e7eb',
        padding: '12px 0'
      }}>
        <div className="container">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '12px' }}>
            <div>
              <h1 style={{ fontSize: '24px', fontWeight: '600', margin: 0 }}>
                📊 Readiness Report
              </h1>
              <p style={{ color: '#6b7280', fontSize: '14px', margin: 0 }}>
                Your defensible proof of skill readiness
              </p>
            </div>
            <div style={{ display: 'flex', gap: '12px' }}>
              <button
                onClick={handlePrint}
                className="btn btn-outline-secondary"
                style={{ display: 'flex', alignItems: 'center', gap: '6px' }}
              >
                🖨️ Print
              </button>
              <button
                onClick={handleExportPDF}
                className="btn btn-primary"
                disabled={isExporting}
                style={{ display: 'flex', alignItems: 'center', gap: '6px' }}
              >
                {isExporting ? (
                  <>
                    <span className="spinner-border spinner-border-sm" role="status" />
                    Exporting...
                  </>
                ) : (
                  <>📄 Export PDF</>
                )}
              </button>
            </div>
          </div>
        </div>
      </div>
      
      {/* Report Content */}
      <section style={{ backgroundColor: '#f9fafb', minHeight: '100vh', paddingTop: '24px', paddingBottom: '40px' }}>
        <div className="container">
          <div ref={reportRef} id="readiness-report" style={{ maxWidth: '800px', margin: '0 auto', fontFamily: 'system-ui, -apple-system, sans-serif' }}>
            
            {/* ═══════════════════════════════════════════════════════════════
                SECTION 1: HEADER
                Logo, User name, Target role, Generated date
            ═══════════════════════════════════════════════════════════════ */}
            <div style={{
              backgroundColor: '#ffffff',
              padding: '32px',
              borderRadius: '12px 12px 0 0',
              borderBottom: '3px solid #3b82f6'
            }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '16px' }}>
                <div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '12px', padding: '48px', marginBottom: '16px' }}>
                    <img 
                      src="/img/logo/logo_resized1.png" 
                      alt="RoleReady" 
                      style={{ height: '40px', objectFit: 'contain' }}
                      onError={(e) => { e.target.style.display = 'none'; }}
                    />
                    <span style={{ fontSize: '24px', fontWeight: '700', color: '#1f2937' }}>
                      READINESS REPORT
                    </span>
                  </div>
                  <div style={{ display: 'grid', gap: '8px' }}>
                    <div>
                      <span style={{ color: '#6b7280', fontSize: '13px' }}>Candidate: </span>
                      <span style={{ fontWeight: '600', fontSize: '16px', color: '#1f2937' }}>{reportUser?.name || 'N/A'}</span>
                    </div>
                    <div>
                      <span style={{ color: '#6b7280', fontSize: '13px' }}>Target Role: </span>
                      <span style={{ fontWeight: '600', fontSize: '16px', color: '#3b82f6' }}>
                        {reportUser?.target_role?.category_name || 'Not specified'}
                      </span>
                    </div>
                  </div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: '13px', color: '#6b7280' }}>Generated on</div>
                  <div style={{ fontSize: '16px', fontWeight: '600', color: '#1f2937' }}>
                    {new Date(report?.generated_at).toLocaleDateString('en-US', {
                      year: 'numeric',
                      month: 'long',
                      day: 'numeric'
                    })}
                  </div>
                  <div style={{ fontSize: '12px', color: '#9ca3af', marginTop: '4px' }}>
                    {new Date(report?.generated_at).toLocaleTimeString('en-US', {
                      hour: '2-digit',
                      minute: '2-digit'
                    })}
                  </div>
                </div>
              </div>
            </div>
            
            {/* Report Body */}
            <div style={{
              backgroundColor: '#fff',
              padding: '32px',
              borderRadius: '0 0 12px 12px',
              border: '1px solid #e5e7eb',
              borderTop: 'none'
            }}>
              
              {/* STEP 6: Disclaimer for pending validation */}
              {hasPendingValidation && (
                <div style={{
                  backgroundColor: '#fffbeb',
                  border: '1px solid #fcd34d',
                  borderRadius: '8px',
                  padding: '12px 16px',
                  marginBottom: '24px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '10px'
                }}>
                  <span style={{ fontSize: '20px' }}>⏳</span>
                  <div>
                    <div style={{ fontWeight: '600', color: '#92400e', fontSize: '14px' }}>
                      Validation Pending
                    </div>
                    <div style={{ color: '#a16207', fontSize: '13px' }}>
                      {validation.pending_validation} skill(s) are awaiting mentor review. 
                      Scores may change after validation.
                    </div>
                  </div>
                </div>
              )}
              
              {/* ═══════════════════════════════════════════════════════════════
                  SECTION 2: READINESS SUMMARY
                  Score (%), Status (Ready/Almost/Not Ready), Last calculated
              ═══════════════════════════════════════════════════════════════ */}
              <div style={{ marginBottom: '32px' }}>
                <h2 style={{ 
                  fontSize: '16px', 
                  fontWeight: '600', 
                  color: '#374151', 
                  marginBottom: '16px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                  borderBottom: '2px solid #e5e7eb',
                  paddingBottom: '8px'
                }}>
                  📊 Readiness Summary
                </h2>
                
                <div style={{ display: 'flex', alignItems: 'center', gap: '32px', flexWrap: 'wrap' }}>
                  {/* Score Circle */}
                  <div style={{ 
                    width: '120px', 
                    height: '120px', 
                    borderRadius: '50%',
                    border: `8px solid ${
                      readiness?.status_color === 'danger' ? '#dc2626' :
                      readiness?.status_color === 'warning' ? '#d97706' :
                      readiness?.status_color === 'success' ? '#16a34a' : '#3b82f6'
                    }`,
                    display: 'flex',
                    flexDirection: 'column',
                    alignItems: 'center',
                    justifyContent: 'center',
                    backgroundColor: '#f9fafb'
                  }}>
                    <div style={{ fontSize: '32px', fontWeight: '700', color: '#1f2937', lineHeight: 1 }}>
                      {readiness?.percentage || 0}%
                    </div>
                    <div style={{ fontSize: '11px', color: '#6b7280', marginTop: '2px' }}>SCORE</div>
                  </div>
                  
                  {/* Status & Details */}
                  <div style={{ flex: 1, minWidth: '200px' }}>
                    <div style={{ marginBottom: '12px' }}>
                      <StatusBadge label={readiness?.status_label || 'Unknown'} color={readiness?.status_color} />
                    </div>
                    <div style={{ display: 'grid', gap: '6px', fontSize: '14px' }}>
                      <div>
                        <span style={{ color: '#6b7280' }}>Last calculated: </span>
                        <span style={{ color: '#1f2937' }}>
                          {readiness?.calculated_at 
                            ? new Date(readiness.calculated_at).toLocaleDateString('en-US', {
                                month: 'short', day: 'numeric', year: 'numeric'
                              })
                            : 'Never'}
                        </span>
                      </div>
                      <div>
                        <span style={{ color: '#6b7280' }}>Skills matched: </span>
                        <span style={{ color: '#1f2937' }}>
                          {skill_breakdown?.met_count || 0} of {skill_breakdown?.total_skills || 0}
                        </span>
                      </div>
                      <div>
                        <span style={{ color: '#6b7280' }}>Trend: </span>
                        <span style={{ color: trend.color, fontWeight: '500' }}>
                          {trend.icon} {trend.text || trend.direction}
                        </span>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              
              {/* ═══════════════════════════════════════════════════════════════
                  SECTION 3: SKILL BREAKDOWN (Table Format)
                  Table: Skill | Status | Source | Importance
              ═══════════════════════════════════════════════════════════════ */}
              <div style={{ marginBottom: '32px' }}>
                <h2 style={{ 
                  fontSize: '16px', 
                  fontWeight: '600', 
                  color: '#374151', 
                  marginBottom: '16px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                  borderBottom: '2px solid #e5e7eb',
                  paddingBottom: '8px'
                }}>
                  ✅ Skill Breakdown
                  <span style={{ fontSize: '13px', fontWeight: '400', color: '#6b7280' }}>
                    ({skill_breakdown?.met_count || 0} met, {skill_breakdown?.missing_count || 0} missing)
                  </span>
                </h2>
                
                <div style={{ overflowX: 'auto' }}>
                  <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '14px' }}>
                    <thead>
                      <tr style={{ backgroundColor: '#f9fafb' }}>
                        <th style={{ textAlign: 'left', padding: '10px 12px', borderBottom: '2px solid #e5e7eb', color: '#374151' }}>Skill</th>
                        <th style={{ textAlign: 'center', padding: '10px 12px', borderBottom: '2px solid #e5e7eb', color: '#374151' }}>Status</th>
                        <th style={{ textAlign: 'center', padding: '10px 12px', borderBottom: '2px solid #e5e7eb', color: '#374151' }}>Source</th>
                        <th style={{ textAlign: 'center', padding: '10px 12px', borderBottom: '2px solid #e5e7eb', color: '#374151' }}>Weight</th>
                        <th style={{ textAlign: 'center', padding: '10px 12px', borderBottom: '2px solid #e5e7eb', color: '#374151' }}>Importance</th>
                      </tr>
                    </thead>
                    <tbody>
                      {allSkills.map((skill, idx) => (
                        <tr key={idx} style={{ 
                          backgroundColor: skill.status === 'met' ? '#f0fdf4' : '#fef2f2',
                          borderBottom: '1px solid #e5e7eb'
                        }}>
                          <td style={{ padding: '10px 12px', fontWeight: '500' }}>
                            {skill.is_validated && <span style={{ color: '#16a34a' }}>✓ </span>}
                            {skill.skill_name}
                          </td>
                          <td style={{ textAlign: 'center', padding: '10px 12px' }}>
                            <StatusBadge 
                              label={skill.status === 'met' ? 'Met' : 'Missing'} 
                              color={skill.status === 'met' ? 'success' : 'danger'}
                              size="small"
                            />
                          </td>
                          <td style={{ textAlign: 'center', padding: '10px 12px', color: '#6b7280' }}>
                            {getSourceLabel(skill.source)}
                          </td>
                          <td style={{ textAlign: 'center', padding: '10px 12px', color: '#6b7280' }}>
                            {skill.weight} pts
                          </td>
                          <td style={{ textAlign: 'center', padding: '10px 12px' }}>
                            {skill.importance === 'required' ? (
                              <span style={{ color: '#dc2626', fontWeight: '500' }}>Required</span>
                            ) : (
                              <span style={{ color: '#6b7280' }}>Optional</span>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
              
              {/* ═══════════════════════════════════════════════════════════════
                  SECTION 4: ROADMAP PRIORITIES
                  High/Medium/Low + Why this matters note
              ═══════════════════════════════════════════════════════════════ */}
              <div style={{ marginBottom: '32px' }}>
                <h2 style={{ 
                  fontSize: '16px', 
                  fontWeight: '600', 
                  color: '#374151', 
                  marginBottom: '16px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                  borderBottom: '2px solid #e5e7eb',
                  paddingBottom: '8px'
                }}>
                  🎯 Roadmap Priorities
                </h2>
                
                {roadmap ? (
                  <>
                    <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '12px', marginBottom: '16px' }}>
                      <div style={{ 
                        padding: '16px', 
                        backgroundColor: '#fef2f2', 
                        borderRadius: '8px',
                        borderLeft: '4px solid #dc2626',
                        textAlign: 'center'
                      }}>
                        <div style={{ fontSize: '28px', fontWeight: '700', color: '#dc2626' }}>
                          {roadmap?.by_priority?.high || 0}
                        </div>
                        <div style={{ fontSize: '12px', color: '#991b1b', fontWeight: '500' }}>🔥 HIGH</div>
                      </div>
                      <div style={{ 
                        padding: '16px', 
                        backgroundColor: '#fffbeb', 
                        borderRadius: '8px',
                        borderLeft: '4px solid #d97706',
                        textAlign: 'center'
                      }}>
                        <div style={{ fontSize: '28px', fontWeight: '700', color: '#d97706' }}>
                          {roadmap?.by_priority?.medium || 0}
                        </div>
                        <div style={{ fontSize: '12px', color: '#92400e', fontWeight: '500' }}>📈 MEDIUM</div>
                      </div>
                      <div style={{ 
                        padding: '16px', 
                        backgroundColor: '#f0fdf4', 
                        borderRadius: '8px',
                        borderLeft: '4px solid #16a34a',
                        textAlign: 'center'
                      }}>
                        <div style={{ fontSize: '28px', fontWeight: '700', color: '#16a34a' }}>
                          {roadmap?.by_priority?.low || 0}
                        </div>
                        <div style={{ fontSize: '12px', color: '#15803d', fontWeight: '500' }}>📋 LOW</div>
                      </div>
                    </div>
                    
                    {/* Top Focus Areas */}
                    {roadmap?.high_priority_items?.length > 0 && (
                      <div style={{ backgroundColor: '#f9fafb', borderRadius: '8px', padding: '16px' }}>
                        <div style={{ fontWeight: '600', fontSize: '14px', marginBottom: '8px', color: '#374151' }}>
                          🔥 Immediate Focus Areas:
                        </div>
                        <ol style={{ paddingLeft: '20px', margin: 0 }}>
                          {roadmap.high_priority_items.slice(0, 3).map((item, idx) => (
                            <li key={idx} style={{ marginBottom: '6px', fontSize: '14px' }}>
                              <strong style={{ color: '#1f2937' }}>{item.skill_name}</strong>
                              <span style={{ color: '#6b7280' }}> — {item.reason}</span>
                            </li>
                          ))}
                        </ol>
                      </div>
                    )}
                    
                    {/* Why this matters */}
                    <div style={{ 
                      marginTop: '12px', 
                      padding: '12px', 
                      backgroundColor: '#eff6ff', 
                      borderRadius: '6px',
                      fontSize: '13px',
                      color: '#1e40af'
                    }}>
                      💡 <strong>Why this matters:</strong> High priority items represent required skills 
                      that are either missing or rejected. Addressing these first will have the biggest 
                      impact on your readiness score.
                    </div>
                  </>
                ) : (
                  <div style={{ 
                    textAlign: 'center', 
                    padding: '24px', 
                    backgroundColor: '#f9fafb', 
                    borderRadius: '8px',
                    color: '#6b7280'
                  }}>
                    <div style={{ fontSize: '32px', marginBottom: '8px' }}>🗺️</div>
                    No roadmap generated yet. Visit the Roadmap page to generate one.
                  </div>
                )}
              </div>
              
              {/* ═══════════════════════════════════════════════════════════════
                  SECTION 5: PROGRESS SNAPSHOT
                  Last 3 readiness scores, Trend direction (up/down/stable)
              ═══════════════════════════════════════════════════════════════ */}
              <div style={{ marginBottom: '32px' }}>
                <h2 style={{ 
                  fontSize: '16px', 
                  fontWeight: '600', 
                  color: '#374151', 
                  marginBottom: '16px',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '8px',
                  borderBottom: '2px solid #e5e7eb',
                  paddingBottom: '8px'
                }}>
                  📈 Progress Snapshot
                  <span style={{ 
                    fontSize: '13px', 
                    fontWeight: '500', 
                    color: trend.color,
                    marginLeft: 'auto'
                  }}>
                    {trend.icon} {trend.text || trend.direction}
                  </span>
                </h2>
                
                {history && history.length > 0 ? (
                  <div style={{ display: 'grid', gap: '12px' }}>
                    {history.slice(0, 3).map((entry, idx) => (
                      <div key={idx} style={{ 
                        display: 'flex', 
                        alignItems: 'center', 
                        gap: '16px',
                        padding: '12px',
                        backgroundColor: idx === 0 ? '#f0fdf4' : '#f9fafb',
                        borderRadius: '8px',
                        border: idx === 0 ? '1px solid #86efac' : '1px solid #e5e7eb'
                      }}>
                        <div style={{ width: '80px', fontSize: '13px', color: '#6b7280' }}>
                          {new Date(entry.calculated_at).toLocaleDateString('en-US', {
                            month: 'short', day: 'numeric'
                          })}
                        </div>
                        <div style={{ flex: 1 }}>
                          <ProgressBar percentage={entry.percentage} color={entry.status_color} height={8} />
                        </div>
                        <div style={{ 
                          width: '50px', 
                          textAlign: 'right', 
                          fontWeight: '600',
                          color: idx === 0 ? '#16a34a' : '#374151'
                        }}>
                          {entry.percentage}%
                        </div>
                        <StatusBadge label={entry.status_label} color={entry.status_color} size="small" />
                      </div>
                    ))}
                  </div>
                ) : (
                  <div style={{ 
                    textAlign: 'center', 
                    padding: '24px', 
                    backgroundColor: '#f9fafb', 
                    borderRadius: '8px',
                    color: '#6b7280'
                  }}>
                    No historical data available yet.
                  </div>
                )}
              </div>
              
              {/* ═══════════════════════════════════════════════════════════════
                  SECTION 6: FOOTER
                  "Generated by RoleReady" + Explainability note
              ═══════════════════════════════════════════════════════════════ */}
              <div style={{
                marginTop: '32px',
                paddingTop: '24px',
                borderTop: '2px solid #e5e7eb'
              }}>
                <div style={{ textAlign: 'center', marginBottom: '16px' }}>
                  <div style={{ fontSize: '14px', fontWeight: '600', color: '#374151' }}>
                    Generated by RoleReady
                  </div>
                  <div style={{ fontSize: '12px', color: '#9ca3af' }}>
                    {new Date(report?.generated_at).toLocaleString()}
                  </div>
                </div>
                
                <div style={{
                  backgroundColor: '#f9fafb',
                  borderRadius: '8px',
                  padding: '16px',
                  fontSize: '12px',
                  color: '#6b7280',
                  lineHeight: '1.6'
                }}>
                  <div style={{ fontWeight: '600', marginBottom: '8px', color: '#374151' }}>
                    📋 Explainability Note
                  </div>
                  <p style={{ margin: '0 0 8px 0' }}>
                    This report is <strong>rule-based and evidence-driven</strong>. Every data point is traceable:
                  </p>
                  <ul style={{ margin: 0, paddingLeft: '20px' }}>
                    <li>Readiness scores are calculated from skill matches against role requirements</li>
                    <li>Skills are sourced from self-claims, resume parsing, or mentor validation</li>
                    <li>Roadmap priorities follow 5 deterministic rules (no AI interpretation)</li>
                    <li>All calculations are reproducible and auditable</li>
                  </ul>
                </div>
              </div>
              
            </div>
          </div>
        </div>
      </section>
      
      {/* Print Styles */}
      <style>{`
        @media print {
          .no-print {
            display: none !important;
          }
          
          body {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
          }
          
          #readiness-report {
            max-width: 100% !important;
            margin: 0 !important;
          }
          
          section {
            padding-top: 0 !important;
            background-color: #fff !important;
          }
        }
      `}</style>
      
      <Footer4 />
    </>
  );
};

export default ReadinessReportPage;
